In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3) + 10

In [3]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [4]:
np.argmin(a)

0

In [5]:
np.min(a)

10

In [6]:
np.argmin(a, axis=0)

array([0, 0, 0], dtype=int64)

In [7]:
np.argmin(a, axis=1)

array([0, 0], dtype=int64)

In [8]:
b = np.arange(6) + 10

In [9]:
b

array([10, 11, 12, 13, 14, 15])

In [10]:
b[4] = 10

In [11]:
b

array([10, 11, 12, 13, 10, 15])

In [12]:
np.argmin(b)

0

In [13]:
x = np.arange(24).reshape((2, 3, 4))

In [14]:
res = np.argmin(x, axis=1, keepdims=True)

In [15]:
res.shape

(2, 1, 4)